server:
  port: 8080
spring:
  application:
    name: task-manage
  main:
    allow-bean-definition-overriding: true
  datasource:
    druid:
      #用来区分多数据源时候的名称，prefix表示参数的前缀
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.189.128:3306/task_manage?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
      username: root
      password: 123456
      #filters: stat, wall, log4j2
      initial-size: 10
      minIdle: 10
      max-active: 100
      maxWait: 180000
      test-on-borrow: true
      stat-view-servlet:
        login-username: druid
        login-password: druid_xrisk


#mybatis-plus:
#  mapperLocations: classpath:mapper/*.xml # xml文件位置
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml,classpath*:mapper/ext/*.xml # xml文件位置

logging:
  level:
    com.yleducation: INFO
  config: classpath:logback-spring.xml
  path: ./logs/

