package com.boxpractice.taskmanage.mapper;

import com.boxpractice.taskmanage.bean.po.Hospital;
import com.boxpractice.taskmanage.bean.po.HospitalExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HospitalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbg.generated Fri Oct 28 21:06:02 CST 2022
     */
    long countByExample(HospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbg.generated Fri Oct 28 21:06:02 CST 2022
     */
    int deleteByExample(HospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbg.generated Fri Oct 28 21:06:02 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbg.generated Fri Oct 28 21:06:02 CST 2022
     */
    int insert(Hospital record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbg.generated Fri Oct 28 21:06:02 CST 2022
     */
    int insertSelective(Hospital record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbg.generated Fri Oct 28 21:06:02 CST 2022
     */
    List<Hospital> selectByExample(HospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbg.generated Fri Oct 28 21:06:02 CST 2022
     */
    Hospital selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbg.generated Fri Oct 28 21:06:02 CST 2022
     */
    int updateByExampleSelective(@Param("record") Hospital record, @Param("example") HospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbg.generated Fri Oct 28 21:06:02 CST 2022
     */
    int updateByExample(@Param("record") Hospital record, @Param("example") HospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbg.generated Fri Oct 28 21:06:02 CST 2022
     */
    int updateByPrimaryKeySelective(Hospital record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbg.generated Fri Oct 28 21:06:02 CST 2022
     */
    int updateByPrimaryKey(Hospital record);
}