package com.boxpractice.taskmanage.bean.po;

import java.util.Date;

public class Employee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.id
     *
     * @mbg.generated Fri Oct 28 21:06:02 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.name
     *
     * @mbg.generated Fri Oct 28 21:06:02 CST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.hospital_id
     *
     * @mbg.generated Fri Oct 28 21:06:02 CST 2022
     */
    private Integer hospitalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.create_user
     *
     * @mbg.generated Fri Oct 28 21:06:02 CST 2022
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.create_time
     *
     * @mbg.generated Fri Oct 28 21:06:02 CST 2022
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.update_user
     *
     * @mbg.generated Fri Oct 28 21:06:02 CST 2022
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.update_time
     *
     * @mbg.generated Fri Oct 28 21:06:02 CST 2022
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.id
     *
     * @return the value of employee.id
     *
     * @mbg.generated Fri Oct 28 21:06:02 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.id
     *
     * @param id the value for employee.id
     *
     * @mbg.generated Fri Oct 28 21:06:02 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.name
     *
     * @return the value of employee.name
     *
     * @mbg.generated Fri Oct 28 21:06:02 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.name
     *
     * @param name the value for employee.name
     *
     * @mbg.generated Fri Oct 28 21:06:02 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.hospital_id
     *
     * @return the value of employee.hospital_id
     *
     * @mbg.generated Fri Oct 28 21:06:02 CST 2022
     */
    public Integer getHospitalId() {
        return hospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.hospital_id
     *
     * @param hospitalId the value for employee.hospital_id
     *
     * @mbg.generated Fri Oct 28 21:06:02 CST 2022
     */
    public void setHospitalId(Integer hospitalId) {
        this.hospitalId = hospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.create_user
     *
     * @return the value of employee.create_user
     *
     * @mbg.generated Fri Oct 28 21:06:02 CST 2022
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.create_user
     *
     * @param createUser the value for employee.create_user
     *
     * @mbg.generated Fri Oct 28 21:06:02 CST 2022
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.create_time
     *
     * @return the value of employee.create_time
     *
     * @mbg.generated Fri Oct 28 21:06:02 CST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.create_time
     *
     * @param createTime the value for employee.create_time
     *
     * @mbg.generated Fri Oct 28 21:06:02 CST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.update_user
     *
     * @return the value of employee.update_user
     *
     * @mbg.generated Fri Oct 28 21:06:02 CST 2022
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.update_user
     *
     * @param updateUser the value for employee.update_user
     *
     * @mbg.generated Fri Oct 28 21:06:02 CST 2022
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.update_time
     *
     * @return the value of employee.update_time
     *
     * @mbg.generated Fri Oct 28 21:06:02 CST 2022
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.update_time
     *
     * @param updateTime the value for employee.update_time
     *
     * @mbg.generated Fri Oct 28 21:06:02 CST 2022
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}