package com.boxpractice.taskmanage.bean.po;

import java.util.Date;

public class Hospital {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.id
     *
     * @mbg.generated Fri Oct 28 21:06:02 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.name
     *
     * @mbg.generated Fri Oct 28 21:06:02 CST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.create_user
     *
     * @mbg.generated Fri Oct 28 21:06:02 CST 2022
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.create_time
     *
     * @mbg.generated Fri Oct 28 21:06:02 CST 2022
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.update_user
     *
     * @mbg.generated Fri Oct 28 21:06:02 CST 2022
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.update_time
     *
     * @mbg.generated Fri Oct 28 21:06:02 CST 2022
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.id
     *
     * @return the value of hospital.id
     *
     * @mbg.generated Fri Oct 28 21:06:02 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.id
     *
     * @param id the value for hospital.id
     *
     * @mbg.generated Fri Oct 28 21:06:02 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.name
     *
     * @return the value of hospital.name
     *
     * @mbg.generated Fri Oct 28 21:06:02 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.name
     *
     * @param name the value for hospital.name
     *
     * @mbg.generated Fri Oct 28 21:06:02 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.create_user
     *
     * @return the value of hospital.create_user
     *
     * @mbg.generated Fri Oct 28 21:06:02 CST 2022
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.create_user
     *
     * @param createUser the value for hospital.create_user
     *
     * @mbg.generated Fri Oct 28 21:06:02 CST 2022
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.create_time
     *
     * @return the value of hospital.create_time
     *
     * @mbg.generated Fri Oct 28 21:06:02 CST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.create_time
     *
     * @param createTime the value for hospital.create_time
     *
     * @mbg.generated Fri Oct 28 21:06:02 CST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.update_user
     *
     * @return the value of hospital.update_user
     *
     * @mbg.generated Fri Oct 28 21:06:02 CST 2022
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.update_user
     *
     * @param updateUser the value for hospital.update_user
     *
     * @mbg.generated Fri Oct 28 21:06:02 CST 2022
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.update_time
     *
     * @return the value of hospital.update_time
     *
     * @mbg.generated Fri Oct 28 21:06:02 CST 2022
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.update_time
     *
     * @param updateTime the value for hospital.update_time
     *
     * @mbg.generated Fri Oct 28 21:06:02 CST 2022
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}